(()=>{'use strict';
const WORK='mavik.workshop.orchestrator.v1',ACCOUNTS='jarvis-accounts',SESSION='jarvis-session',AUDIT='mavik-audit-log',NOTIFS='mavik-workshop-notifications',CALLS='mavik-internal-calls',OUTBOX='mavik-workshop-sync-outbox',AI='mavik-ai-requests';
const STEPS=['Accueil et ouverture du dossier','Contrôle administratif et demande client','Photos avant intervention','Inspection réelle du véhicule','Validation du devis définitif','Préparation de la zone et du véhicule','Cryonettoyage','Application Dinitrol si prévue','Contrôle qualité final','Rapport, paiement et restitution'];
const $=id=>document.getElementById(id),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const read=(store,key,fallback)=>{try{return JSON.parse(store.getItem(key)||'null')??fallback}catch{return fallback}},write=(store,key,value)=>store.setItem(key,JSON.stringify(value));
const uid=()=>crypto.randomUUID?.()||`${Date.now()}-${Math.random().toString(16).slice(2)}`;
let user=null,selectedId=null,cameraStream=null,recognition=null,listening=false,activePanel='dashboard',clockTimer=null,refreshTimer=null,reminderTimer=null;
function defaultState(){return{environment:{humidity:55},resources:[{id:'dry-ice',name:'Glace carbonique',quantity:0,unit:'kg'},{id:'dinitrol-stock',name:'DINITROL',quantity:0,unit:'L'},{id:'pit',name:'Fosse atelier',status:'AVAILABLE'}],audit:[],interventions:[]}}
function state(){const value=read(localStorage,WORK,defaultState());value.environment=value.environment||{humidity:55};value.resources=Array.isArray(value.resources)?value.resources:[];value.audit=Array.isArray(value.audit)?value.audit:[];value.interventions=Array.isArray(value.interventions)?value.interventions:[];return value}
function saveState(value){write(localStorage,WORK,value)}
function normalize(item){item.client=item.client||{};item.vehicle=item.vehicle||{};item.quote=item.quote||{};item.logistics=item.logistics||{};item.workflow=item.workflow||{};item.workflow.steps=Array.isArray(item.workflow.steps)?item.workflow.steps:STEPS.map((label,index)=>({id:`s${index+1}`,label,done:false}));item.photos=item.photos||{};for(const stage of ['before','during','after'])item.photos[stage]=Array.isArray(item.photos[stage])?item.photos[stage]:[];item.report=item.report||{};return item}
function interventions(){return state().interventions.map(normalize)}
function saveIntervention(item){const s=state(),index=s.interventions.findIndex(entry=>entry.id===item.id);item.updatedAt=new Date().toISOString();if(index>=0)s.interventions[index]=item;else s.interventions.unshift(item);s.audit.push({at:new Date().toISOString(),type:'workshop.station.saved',interventionId:item.id,user:'Atelier'});s.audit=s.audit.slice(-1500);saveState(s);queueSync('intervention.updated',{interventionId:item.id});return item}
function ensureAtelier(){const accounts=read(localStorage,ACCOUNTS,[]);let account=accounts.find(entry=>entry.id==='atelier');if(!account){account={id:'atelier',name:'Atelier',role:'workshop',pin:null,autoLogin:true};accounts.push(account);write(localStorage,ACCOUNTS,accounts)}const params=new URLSearchParams(location.search),existing=read(sessionStorage,SESSION,null);if(params.get('station')==='atelier'||!existing){write(sessionStorage,SESSION,{id:'atelier',role:'workshop',station:true,temporary:false,openedAt:new Date().toISOString()});user=account}else user=accounts.find(entry=>entry.id===existing.id)||account;audit('station.opened',{station:'atelier',role:user.role})}
function audit(action,details={}){const log=read(localStorage,AUDIT,[]);log.unshift({id:uid(),at:new Date().toISOString(),userId:user?.id||'atelier',userName:user?.name||'Atelier',role:user?.role||'workshop',module:'workshop-station',action,details});write(localStorage,AUDIT,log.slice(0,4000))}
function queueSync(type,payload={}){const queue=read(localStorage,OUTBOX,[]);queue.unshift({id:uid(),at:new Date().toISOString(),type,payload,status:'pending'});write(localStorage,OUTBOX,queue.slice(0,2000));updateConnection()}
function addNotification(title,message,type='info'){const list=read(localStorage,NOTIFS,[]),record={id:uid(),at:new Date().toISOString(),title,message,type,status:'unread'};list.unshift(record);write(localStorage,NOTIFS,list.slice(0,500));const host=$('notifications');if(host){const el=document.createElement('div');el.className='notice';el.innerHTML=`<strong>${esc(title)}</strong><small>${esc(message)}</small>`;host.prepend(el);setTimeout(()=>el.remove(),7000)}queueSync('notification.created',record);return record}
function todayKey(date=new Date()){return date.toISOString().slice(0,10)}
function startDate(item){return item.logistics?.interventionAt?new Date(item.logistics.interventionAt):null}
function durationHours(item){return Math.max(1,Number(item.logistics?.duration||4))}
function completed(item){return Boolean(item.workflow?.completedAt)||item.workflow.steps.every(step=>step.done)}
function itemStatus(item,now=new Date()){if(completed(item))return'done';if(item.workflow?.startedAt)return'current';const start=startDate(item);if(!start)return'upcoming';const end=new Date(start.getTime()+durationHours(item)*3600000);if(now>end)return'late';if(now>=start&&now<=end)return'current';return'upcoming'}
function dayItems(day=todayKey()){return interventions().filter(item=>String(item.logistics?.interventionAt||'').slice(0,10)===day).sort((a,b)=>String(a.logistics.interventionAt).localeCompare(String(b.logistics.interventionAt)))}
function currentAndNext(){const items=dayItems(),now=new Date();let current=items.find(item=>itemStatus(item,now)==='current')||items.find(item=>itemStatus(item,now)==='late')||items.find(item=>itemStatus(item,now)==='upcoming')||null;if(selectedId){const selected=items.find(item=>item.id===selectedId)||interventions().find(item=>item.id===selectedId);if(selected)current=selected}const currentStart=current?startDate(current):null;const next=items.find(item=>item.id!==current?.id&&itemStatus(item,now)==='upcoming'&&(!currentStart||startDate(item)>currentStart))||items.find(item=>item.id!==current?.id&&itemStatus(item,now)!=='done')||null;return{current,next,items}}
function statusLabel(status){return{done:'Terminé',current:'En cours',upcoming:'À venir',late:'Retard'}[status]||status}
function formatTime(value){if(!value)return'--:--';const date=new Date(value);return Number.isNaN(date.getTime())?'--:--':date.toLocaleTimeString('fr-FR',{hour:'2-digit',minute:'2-digit'})}
function buildShell(){document.body.innerHTML=`<div class="station"><header class="station-header"><div class="brand"><img src="../../assets/brand/gentlecare-logo.png" alt="GentleCarE"><div><small>MAVIK GCOS · POSTE OPÉRATEUR</small><h1>Atelier</h1></div></div><div class="clock"><strong id="clock">--:--:--</strong><span id="date">--</span></div><div class="header-status"><span class="badge ok">● Profil Atelier</span><span class="badge" id="networkBadge">Réseau</span><span class="badge" id="cameraBadge">Caméra</span><div class="toolbar"><button class="btn blue" id="activateStation">Activer son et caméra</button><button class="btn" id="fullscreen">Plein écran</button></div></div></header><div class="station-body"><nav class="station-nav"><button class="active" data-panel="dashboard">⌂ Tableau de bord</button><button data-panel="intervention">🛠 Intervention</button><button data-panel="photos">📷 Photos</button><button data-panel="report">📄 Rapport</button><button data-panel="stock">📦 Stock</button><button data-panel="voice">🎙 Assistance vocale</button><div class="locked">Accès limité au poste opérateur.<br>Administration, banque, comptabilité, utilisateurs, GitHub et paramètres système non chargés.</div></nav><main class="content"><section class="panel" id="panel-dashboard"></section><section class="panel" id="panel-intervention" hidden></section><section class="panel" id="panel-photos" hidden></section><section class="panel" id="panel-report" hidden></section><section class="panel" id="panel-stock" hidden></section><section class="panel" id="panel-voice" hidden></section></main></div><div class="notifications" id="notifications"></div></div>`;bindShell();tick();renderAll()}
function bindShell(){document.querySelectorAll('[data-panel]').forEach(button=>button.onclick=()=>openPanel(button.dataset.panel));$('activateStation').onclick=activateStation;$('fullscreen').onclick=()=>document.documentElement.requestFullscreen?.().catch(()=>{});window.addEventListener('online',updateConnection);window.addEventListener('offline',updateConnection)}
function openPanel(name){activePanel=name;document.querySelectorAll('[data-panel]').forEach(button=>button.classList.toggle('active',button.dataset.panel===name));document.querySelectorAll('.panel').forEach(panel=>panel.hidden=panel.id!==`panel-${name}`);if(name==='photos')renderPhotos();if(name==='intervention')renderIntervention();if(name==='report')renderReport();if(name==='stock')renderStock();if(name==='voice')renderVoice()}
function tick(){const now=new Date();if($('clock'))$('clock').textContent=now.toLocaleTimeString('fr-FR',{hour:'2-digit',minute:'2-digit',second:'2-digit'});if($('date'))$('date').textContent=now.toLocaleDateString('fr-FR',{weekday:'long',day:'2-digit',month:'long',year:'numeric'});updateNowLine(now)}
function updateConnection(){if(!$('networkBadge'))return;const pending=read(localStorage,OUTBOX,[]).filter(entry=>entry.status==='pending').length;$('networkBadge').textContent=navigator.onLine?`Ethernet / réseau · ${pending} à synchroniser`:`Hors ligne · ${pending} en attente`;$('networkBadge').className=`badge ${navigator.onLine?'ok':'warn'}`}
function interventionCard(item,kind){if(!item)return'<div class="empty">Aucune intervention.</div>';const status=itemStatus(item);return `<article class="intervention-card ${status} ${kind}"><div class="intervention-title"><div><strong>${esc(item.vehicle.name||'Véhicule à renseigner')}</strong><div class="muted">${esc(item.client.name||'Client')} · ${esc(item.vehicle.registration||'Sans immatriculation')}</div></div><span class="status ${status}">${statusLabel(status)}</span></div><div class="intervention-meta"><div><small>Heure prévue</small><b>${formatTime(item.logistics.interventionAt)}</b></div><div><small>Durée</small><b>${durationHours(item)} h</b></div><div><small>Opérateur</small><b>${esc(item.logistics.operator||'Atelier')}</b></div><div><small>Forfait</small><b>${esc(item.quote.package||'À préciser')}</b></div></div><p>${esc(item.quote.request||item.clientRequest||'Demande à compléter')}</p><div class="toolbar"><button class="btn primary" data-select="${item.id}">Ouvrir</button>${kind==='current'&&!completed(item)?'<button class="btn blue" id="quickStart">Démarrer</button><button class="btn red" id="quickComplete">Terminer</button>':''}</div></article>`}
function renderDashboard(){const {current,next,items}=currentAndNext();if(current&&!selectedId)selectedId=current.id;$('panel-dashboard').innerHTML=`<div class="dashboard-grid"><article class="card"><div class="card-head"><div><h2>Caméra Atelier</h2><div class="muted">Logitech USB HD 1080p</div></div><button class="btn" id="restartCamera">Relancer la caméra</button></div><div class="camera-wrap"><video id="camera" autoplay muted playsinline></video><div class="camera-placeholder" id="cameraPlaceholder">Caméra en attente d’autorisation.<br>Utilisez « Activer son et caméra ».</div><div class="camera-overlay"><span id="cameraName">Caméra USB</span><span class="badge live">DIRECT</span></div></div></article><div style="display:grid;gap:12px"><article class="card"><div class="card-head"><div><h2>Intervention en cours</h2><div class="muted">Dossier opérateur actif</div></div></div>${interventionCard(current,'current')}</article><article class="card"><div class="card-head"><div><h2>Intervention suivante</h2><div class="muted">Prochaine heure prévue</div></div></div>${interventionCard(next,'next')}</article></div><article class="card timeline-card"><div class="card-head"><div><h2>Planning journalier</h2><div class="muted">Vert terminé · bleu en cours · blanc à venir · rouge retard</div></div><span class="badge">${items.length} intervention(s)</span></div><div class="timeline-scroll"><div class="hour-labels">${Array.from({length:11},(_,index)=>`<span>${String(8+index).padStart(2,'0')}:00</span>`).join('')}</div><div class="timeline" id="timeline">${timelineEvents(items)}<div class="now-line" id="nowLine"></div></div></div></article></div>`;bindDashboard();attachCamera();updateNowLine(new Date())}
function timelineEvents(items){const startDay=8*60,total=10*60;return items.map(item=>{const date=startDate(item);if(!date)return'';const minute=date.getHours()*60+date.getMinutes(),left=Math.max(0,Math.min(100,(minute-startDay)/total*100)),width=Math.max(2,Math.min(100-left,durationHours(item)*60/total*100)),status=itemStatus(item);return `<button class="timeline-event ${status}" data-select="${item.id}" style="left:${left}%;width:${width}%"><strong>${esc(item.vehicle.name||'Véhicule')}</strong><small>${formatTime(item.logistics.interventionAt)} · ${esc(item.client.name||'Client')}</small></button>`}).join('')}
function updateNowLine(now){const line=$('nowLine');if(!line)return;const minute=now.getHours()*60+now.getMinutes(),left=(minute-8*60)/(10*60)*100;line.style.display=left<0||left>100?'none':'block';line.style.left=`${Math.max(0,Math.min(100,left))}%`}
function bindDashboard(){document.querySelectorAll('[data-select]').forEach(button=>button.onclick=()=>{selectedId=button.dataset.select;openPanel('intervention');renderDashboard()});$('quickStart')?.addEventListener('click',startCurrent);$('quickComplete')?.addEventListener('click',completeCurrent);$('restartCamera').onclick=startCamera}
function selected(){const all=interventions(),fallback=currentAndNext().current;return all.find(item=>item.id===selectedId)||fallback||all[0]||null}
function renderIntervention(){const item=selected();if(!item){$('panel-intervention').innerHTML='<div class="card empty">Aucun dossier Atelier disponible.</div>';return}selectedId=item.id;const status=itemStatus(item);$('panel-intervention').innerHTML=`<article class="card"><div class="card-head"><div><h2>Intervention · ${esc(item.vehicle.name||'Véhicule')}</h2><div class="muted">${esc(item.client.name||'Client')} · ${esc(item.vehicle.registration||'')}</div></div><span class="status ${status}">${statusLabel(status)}</span></div><div class="intervention-meta"><div><small>Téléphone client</small><b>${esc(item.client.phone||'Non renseigné')}</b></div><div><small>E-mail</small><b>${esc(item.client.email||'Non renseigné')}</b></div><div><small>VIN</small><b>${esc(item.vehicle.vin||'Non renseigné')}</b></div><div><small>Kilométrage</small><b>${esc(item.vehicle.mileage||'Non renseigné')}</b></div><div><small>Heure</small><b>${formatTime(item.logistics.interventionAt)}</b></div><div><small>Forfait</small><b>${esc(item.quote.package||'À préciser')}</b></div></div><h3>Demande client</h3><p>${esc(item.quote.request||item.clientRequest||'À compléter')}</p><div class="toolbar"><button class="btn blue" id="startIntervention">Démarrer l’intervention</button><button class="btn red" id="completeIntervention">Intervention terminée</button><button class="btn" id="openPhotos">Photos</button><button class="btn" id="openReport">Rapport</button></div></article><article class="card" style="margin-top:12px"><div class="card-head"><div><h2>Parcours opérateur</h2><div class="muted">Chaque étape est tracée.</div></div><span class="badge">${item.workflow.steps.filter(step=>step.done).length}/${item.workflow.steps.length}</span></div><div>${item.workflow.steps.map((step,index)=>`<label class="intervention-card ${step.done?'done':''}" style="display:flex;gap:10px;align-items:center;margin-top:7px"><input type="checkbox" data-step="${index}" ${step.done?'checked':''}><span><strong>${index+1}. ${esc(step.label)}</strong></span></label>`).join('')}</div></article>`;$('startIntervention').onclick=startCurrent;$('completeIntervention').onclick=completeCurrent;$('openPhotos').onclick=()=>openPanel('photos');$('openReport').onclick=()=>openPanel('report');document.querySelectorAll('[data-step]').forEach(input=>input.onchange=()=>{item.workflow.steps[Number(input.dataset.step)].done=input.checked;saveIntervention(item);audit('workflow.step.changed',{interventionId:item.id,step:Number(input.dataset.step),done:input.checked});renderIntervention();renderDashboard()})}
function startCurrent(){const item=selected();if(!item)return notifyError('Aucune intervention à démarrer.');if(completed(item))return notifyError('Cette intervention est déjà terminée.');item.workflow.startedAt=item.workflow.startedAt||new Date().toISOString();item.workflow.steps[0].done=true;saveIntervention(item);audit('intervention.started',{interventionId:item.id});addNotification('Intervention démarrée',`${item.vehicle.name||'Véhicule'} · ${item.client.name||'Client'}`,'current');speak(`Intervention ${item.vehicle.name||''} démarrée.`);renderAll();openPanel('intervention')}
function completeCurrent(){const item=selected();if(!item)return notifyError('Aucune intervention active.');if(!confirm(`Confirmer la fin de l’intervention ${item.vehicle.name||''} ?`))return;item.workflow.startedAt=item.workflow.startedAt||new Date().toISOString();item.workflow.completedAt=new Date().toISOString();item.workflow.steps.forEach(step=>step.done=true);saveIntervention(item);audit('intervention.completed',{interventionId:item.id});addNotification('Fin d’intervention',`${item.vehicle.name||'Véhicule'} est terminé.`,'done');speak(`Intervention terminée. ${nextAnnouncement()}`);renderAll();openPanel('dashboard')}
function renderPhotos(){const item=selected();if(!item){$('panel-photos').innerHTML='<div class="card empty">Aucune intervention sélectionnée.</div>';return}$('panel-photos').innerHTML=`<article class="card"><div class="card-head"><div><h2>Photos · ${esc(item.vehicle.name||'Véhicule')}</h2><div class="muted">Avant, pendant et après intervention</div></div><button class="btn" id="cameraPhotos">Activer la caméra</button></div><div class="photo-actions"><button class="btn yellow" data-capture="before">Photo avant</button><button class="btn blue" data-capture="during">Photo pendant</button><button class="btn primary" data-capture="after">Photo après</button><label class="btn">Importer des photos<input id="photoImport" type="file" accept="image/*" multiple hidden></label></div>${['before','during','after'].map(stage=>`<h3 style="margin-top:18px">${{before:'Avant',during:'Pendant',after:'Après'}[stage]} (${item.photos[stage].length})</h3><div class="photo-grid">${item.photos[stage].map(photo=>`<article class="photo"><img src="${photo.data}" alt="Photo ${stage}"><small>${new Date(photo.at).toLocaleString('fr-FR')}</small></article>`).join('')||'<div class="empty">Aucune photo.</div>'}</div>`).join('')}</article>`;$('cameraPhotos').onclick=startCamera;document.querySelectorAll('[data-capture]').forEach(button=>button.onclick=()=>capturePhoto(button.dataset.capture));$('photoImport').onchange=event=>importPhotos(event.target.files)}
async function startCamera(){const video=$('camera');if(!video){openPanel('dashboard');await new Promise(resolve=>setTimeout(resolve,50))}try{cameraStream?.getTracks().forEach(track=>track.stop());let stream=await navigator.mediaDevices.getUserMedia({video:{width:{ideal:1920},height:{ideal:1080}},audio:false});const devices=await navigator.mediaDevices.enumerateDevices(),logitech=devices.find(device=>device.kind==='videoinput'&&/logitech/i.test(device.label));if(logitech){stream.getTracks().forEach(track=>track.stop());stream=await navigator.mediaDevices.getUserMedia({video:{deviceId:{exact:logitech.deviceId},width:{ideal:1920},height:{ideal:1080}},audio:false})}cameraStream=stream;const target=$('camera');if(target){target.srcObject=stream;await target.play().catch(()=>{});$('cameraPlaceholder').style.display='none';$('cameraName').textContent=stream.getVideoTracks()[0]?.label||'Caméra USB'}$('cameraBadge').textContent='Caméra active';$('cameraBadge').className='badge ok';audit('camera.started',{label:stream.getVideoTracks()[0]?.label||''});return true}catch(error){$('cameraBadge').textContent='Caméra à autoriser';$('cameraBadge').className='badge warn';if($('cameraPlaceholder'))$('cameraPlaceholder').innerHTML=`Caméra indisponible.<br>${esc(error.message||error)}<br><button class="btn" id="cameraRetry">Autoriser la caméra</button>`;setTimeout(()=>{if($('cameraRetry'))$('cameraRetry').onclick=startCamera},0);audit('camera.failed',{message:error.message});return false}}
async function capturePhoto(stage){const item=selected();if(!item)return notifyError('Aucun dossier sélectionné.');if(!cameraStream&&!(await startCamera()))return;const video=$('camera');if(!video||!video.videoWidth)return notifyError('La caméra n’est pas encore prête.');const canvas=document.createElement('canvas'),scale=Math.min(1,1280/video.videoWidth);canvas.width=Math.round(video.videoWidth*scale);canvas.height=Math.round(video.videoHeight*scale);canvas.getContext('2d').drawImage(video,0,0,canvas.width,canvas.height);const photo={id:uid(),at:new Date().toISOString(),stage,data:canvas.toDataURL('image/jpeg',.72),source:'camera'};item.photos[stage].unshift(photo);item.photos[stage]=item.photos[stage].slice(0,20);try{saveIntervention(item)}catch(error){item.photos[stage].shift();return notifyError('Stockage photo saturé. Exportez les données avant de continuer.')}audit('photo.captured',{interventionId:item.id,stage});queueSync('photo.created',{interventionId:item.id,photoId:photo.id,stage});addNotification(`Photo ${stage==='before'?'avant':stage==='during'?'pendant':'après'}`,item.vehicle.name||'Véhicule');speak(`Photo ${stage==='before'?'avant':stage==='during'?'pendant':'après'} enregistrée.`);renderPhotos()}
async function importPhotos(files){const item=selected();if(!item||!files?.length)return;for(const file of [...files].slice(0,12)){const data=await fileToData(file);item.photos.during.unshift({id:uid(),at:new Date().toISOString(),stage:'during',data,source:'import',name:file.name})}item.photos.during=item.photos.during.slice(0,20);saveIntervention(item);audit('photos.imported',{interventionId:item.id,count:files.length});renderPhotos()}
function fileToData(file){return new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.onerror=reject;reader.readAsDataURL(file)})}
function renderReport(){const item=selected();if(!item){$('panel-report').innerHTML='<div class="card empty">Aucune intervention sélectionnée.</div>';return}$('panel-report').innerHTML=`<article class="card"><div class="card-head"><div><h2>Rapport · ${esc(item.vehicle.name||'Véhicule')}</h2><div class="muted">Compte rendu opérateur transmis à la Direction.</div></div><span class="badge">${item.workflow.steps.filter(step=>step.done).length}/${item.workflow.steps.length} étapes</span></div><form class="form-grid" id="reportForm"><label class="wide">Résumé de l’intervention<textarea name="summary" data-voice-name="résumé rapport">${esc(item.report.summary||'')}</textarea></label><label class="wide">Observations et réserves<textarea name="observations" data-voice-name="observations">${esc(item.report.observations||'')}</textarea></label><label>Contrôle qualité<input name="quality" value="${esc(item.report.quality||'À réaliser')}"></label><label>Restitution prévue<input name="returnAt" type="datetime-local" value="${item.report.returnAt?String(item.report.returnAt).slice(0,16):''}"></label><div class="wide toolbar"><button class="btn primary">Enregistrer le rapport</button><button class="btn" type="button" id="completeFromReport">Terminer l’intervention</button></div></form></article>`;$('reportForm').onsubmit=event=>{event.preventDefault();item.report={...item.report,...Object.fromEntries(new FormData(event.target)),updatedAt:new Date().toISOString(),operator:user?.name||'Atelier'};saveIntervention(item);audit('report.saved',{interventionId:item.id});addNotification('Rapport enregistré',item.vehicle.name||'Véhicule');speak('Rapport enregistré.');renderReport()};$('completeFromReport').onclick=completeCurrent}
function renderStock(){const s=state(),resource=id=>s.resources.find(entry=>entry.id===id)||{};const ice=resource('dry-ice'),dinitrol=resource('dinitrol-stock'),pit=s.resources.find(entry=>['pit','lift'].includes(entry.id))||{};$('panel-stock').innerHTML=`<article class="card"><div class="card-head"><div><h2>Stock Atelier · lecture seule</h2><div class="muted">Les modifications sont réservées à la Gestion.</div></div><span class="badge">Dernière lecture ${new Date().toLocaleTimeString('fr-FR',{hour:'2-digit',minute:'2-digit'})}</span></div><div class="stock-grid"><div class="stock-item"><span>Glace carbonique</span><strong>${Number(ice.quantity||0)} kg</strong></div><div class="stock-item"><span>DINITROL disponible</span><strong>${Number(dinitrol.quantity||0)} L</strong></div><div class="stock-item"><span>Fosse Atelier</span><strong>${esc(pit.status||'AVAILABLE')}</strong></div><div class="stock-item"><span>Humidité</span><strong>${Number(s.environment?.humidity||0)} %</strong></div><div class="stock-item"><span>Photos en attente synchro</span><strong>${read(localStorage,OUTBOX,[]).filter(entry=>entry.type==='photo.created'&&entry.status==='pending').length}</strong></div><div class="stock-item"><span>État réseau</span><strong>${navigator.onLine?'Connecté':'Hors ligne'}</strong></div></div></article>`}
function renderVoice(){$('panel-voice').innerHTML=`<article class="card"><div class="card-head"><div><h2>Assistance vocale MAVIK</h2><div class="muted">Les commandes sont limitées aux fonctions Atelier.</div></div><span class="badge" id="voiceStatus">Prêt</span></div><div class="voice-box"><div><div class="voice-transcript" id="voiceTranscript">Dites « Mavik, démarre l’intervention » ou utilisez le bouton.</div><div class="tabs-row" style="margin-top:10px"><button class="btn" data-command="démarre l'intervention">Démarrer</button><button class="btn" data-command="photo avant">Photo avant</button><button class="btn" data-command="intervention terminée">Terminer</button><button class="btn" data-command="prochaine intervention">Suivante</button><button class="btn" data-command="appelle David">Appeler David</button></div></div><button class="voice-button" id="voiceButton">🎙</button></div><h3 style="margin-top:18px">Commandes autorisées</h3><div class="stock-grid"><div class="stock-item"><span>Intervention</span><strong style="font-size:1rem">Démarre / termine</strong></div><div class="stock-item"><span>Photos</span><strong style="font-size:1rem">Avant / pendant / après</strong></div><div class="stock-item"><span>Navigation</span><strong style="font-size:1rem">Suivante / fiche véhicule</strong></div><div class="stock-item"><span>Communication</span><strong style="font-size:1rem">Appelle David</strong></div></div></article>`;$('voiceButton').onclick=toggleVoice;document.querySelectorAll('[data-command]').forEach(button=>button.onclick=()=>executeCommand(button.dataset.command))}
const SpeechRecognition=window.SpeechRecognition||window.webkitSpeechRecognition;
function toggleVoice(){listening?stopVoice():startVoice()}
function startVoice(){if(!SpeechRecognition){setTranscript('Reconnaissance vocale indisponible dans ce navigateur.');return}if(!recognition){recognition=new SpeechRecognition();recognition.lang='fr-FR';recognition.continuous=true;recognition.interimResults=false;recognition.onstart=()=>{listening=true;voiceState('Écoute…',true)};recognition.onresult=event=>{for(let index=event.resultIndex;index<event.results.length;index++)if(event.results[index].isFinal)executeCommand(event.results[index][0].transcript)};recognition.onerror=event=>{setTranscript(`Erreur vocale : ${event.error}`);voiceState('Erreur',false)};recognition.onend=()=>{if(listening)setTimeout(()=>{try{recognition.start()}catch{}},350);else voiceState('Prêt',false)}}try{recognition.start()}catch{} }
function stopVoice(){listening=false;try{recognition?.stop()}catch{}voiceState('Prêt',false)}
function voiceState(text,on){if($('voiceStatus')){$('voiceStatus').textContent=text;$('voiceStatus').className=`badge ${on?'ok':''}`}if($('voiceButton'))$('voiceButton').classList.toggle('listening',on)}
function setTranscript(text){if($('voiceTranscript'))$('voiceTranscript').textContent=text}
function normalizeCommand(text){return String(text||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/^\s*(mavik|jarvis)[,\s:]*/,'').trim()}
function executeCommand(raw){const command=normalizeCommand(raw);setTranscript(`Vous : ${raw}`);audit('voice.command',{command});if(/demarre.*intervention|commence.*intervention/.test(command))return startCurrent();if(/photo.*avant/.test(command))return capturePhoto('before');if(/photo.*pendant/.test(command))return capturePhoto('during');if(/photo.*apres/.test(command))return capturePhoto('after');if(/intervention.*terminee|termine.*intervention|fin.*intervention/.test(command))return completeCurrent();if(/prochaine.*intervention|intervention.*suivante/.test(command)){speak(nextAnnouncement());const next=currentAndNext().next;if(next){selectedId=next.id;renderDashboard()}return}if(/ouvre.*fiche.*vehicule|fiche.*vehicule/.test(command)){openPanel('intervention');return speak('Fiche véhicule ouverte.')}if(/appelle.*david|appel.*david/.test(command))return callDavid();if(/ouvre.*photos/.test(command)){openPanel('photos');return speak('Photos ouvertes.')}if(/ouvre.*rapport/.test(command)){openPanel('report');return speak('Rapport ouvert.')}if(/ouvre.*stock/.test(command)){openPanel('stock');return speak('Stock ouvert en lecture seule.')}const queue=read(localStorage,AI,[]);queue.unshift({id:uid(),at:new Date().toISOString(),request:raw,page:'workshop-station',status:'review-required',userId:'atelier'});write(localStorage,AI,queue.slice(0,500));speak('Commande non reconnue. Elle a été enregistrée pour analyse.')}
function callDavid(){const calls=read(localStorage,CALLS,[]),record={id:uid(),at:new Date().toISOString(),from:'atelier',to:'david',reason:'Appel demandé depuis le Poste Atelier',status:'pending'};calls.unshift(record);write(localStorage,CALLS,calls.slice(0,500));audit('internal.call.requested',{to:'david'});addNotification('Appel interne',"Demande d’appel transmise à David.");queueSync('internal.call.requested',record);speak('Demande d’appel transmise à David.')}
function nextAnnouncement(){const next=currentAndNext().next;if(!next)return'Aucune autre intervention n’est prévue aujourd’hui.';return`Prochaine intervention à ${formatTime(next.logistics.interventionAt)} : ${next.vehicle.name||'véhicule'}, client ${next.client.name||''}.`}
function speak(text){if(!('speechSynthesis'in window))return;window.speechSynthesis.cancel();const utterance=new SpeechSynthesisUtterance(text);utterance.lang='fr-FR';utterance.rate=.96;utterance.pitch=.88;window.speechSynthesis.speak(utterance)}
function startupPhrase(){const {current,next,items}=currentAndNext();let text=`Bonjour. Programme Atelier du ${new Date().toLocaleDateString('fr-FR')}. ${items.length} intervention${items.length>1?'s':''} prévue${items.length>1?'s':''}.`;if(current)text+=` Intervention ${itemStatus(current)==='late'?'en retard':itemStatus(current)==='current'?'en cours':'à venir'} : ${current.vehicle.name||'véhicule'}, ${current.client.name||'client'}, à ${formatTime(current.logistics.interventionAt)}.`;if(next)text+=` ${nextAnnouncement()}`;return text}
async function startupSound(){try{const context=new (window.AudioContext||window.webkitAudioContext)();await context.resume();const now=context.currentTime;[196,294,392,523,659].forEach((frequency,index)=>{const oscillator=context.createOscillator(),gain=context.createGain();oscillator.type=index<2?'sine':'triangle';oscillator.frequency.setValueAtTime(frequency,now+index*.12);gain.gain.setValueAtTime(.0001,now+index*.12);gain.gain.exponentialRampToValueAtTime(.13,now+index*.12+.03);gain.gain.exponentialRampToValueAtTime(.0001,now+index*.12+.32);oscillator.connect(gain).connect(context.destination);oscillator.start(now+index*.12);oscillator.stop(now+index*.12+.34)});return true}catch{return false}}
async function activateStation(){await startupSound();await startCamera();setTimeout(()=>speak(startupPhrase()),750);sessionStorage.setItem(`mavik-workshop-announced-${todayKey()}`,'1');$('activateStation').textContent='Son et caméra actifs';$('activateStation').className='btn primary'}
function autoStartup(){const key=`mavik-workshop-announced-${todayKey()}`;if(!sessionStorage.getItem(key)){startupSound().then(ok=>{if(ok){setTimeout(()=>speak(startupPhrase()),700);sessionStorage.setItem(key,'1')}})}startCamera()}
function checkReminders(){const next=currentAndNext().next;if(!next)return;const start=startDate(next),minutes=start?(start-Date.now())/60000:999;if(minutes>0&&minutes<=15){const key=`mavik-reminder-${next.id}-${todayKey()}`;if(!sessionStorage.getItem(key)){sessionStorage.setItem(key,'1');addNotification('Prochaine intervention',`${next.vehicle.name||'Véhicule'} à ${formatTime(next.logistics.interventionAt)}.`,'reminder');speak(`Rappel. ${nextAnnouncement()}`)}}}
function notifyError(message){addNotification('Action impossible',message,'error');speak(message)}
function attachCamera(){if(cameraStream&&$('camera')){$('camera').srcObject=cameraStream;$('camera').play().catch(()=>{});if($('cameraPlaceholder'))$('cameraPlaceholder').style.display='none';if($('cameraName'))$('cameraName').textContent=cameraStream.getVideoTracks()[0]?.label||'Caméra USB'}}
function renderAll(){renderDashboard();renderIntervention();renderPhotos();renderReport();renderStock();renderVoice();openPanel(activePanel);updateConnection()}
function boot(){try{ensureAtelier();buildShell();clearInterval(clockTimer);clearInterval(refreshTimer);clearInterval(reminderTimer);clockTimer=setInterval(tick,1000);refreshTimer=setInterval(()=>{renderDashboard();if(activePanel==='intervention')renderIntervention();updateConnection()},60000);reminderTimer=setInterval(checkReminders,30000);autoStartup();checkReminders()}catch(error){console.error(error);document.body.innerHTML=`<main style="min-height:100vh;display:grid;place-items:center;background:#031019;color:white;font-family:system-ui;padding:20px"><section style="max-width:720px;border:1px solid #286079;border-radius:18px;background:#071a27;padding:20px"><h1>MAVIK Atelier reste visible</h1><p>Le poste a rencontré une erreur sans effacer les dossiers.</p><pre style="white-space:pre-wrap">${esc(error.stack||error.message||error)}</pre><button onclick="location.reload()" style="padding:12px">Recharger le Poste Atelier</button></section></main>`}}
window.addEventListener('beforeunload',()=>cameraStream?.getTracks().forEach(track=>track.stop()));document.readyState==='loading'?document.addEventListener('DOMContentLoaded',boot,{once:true}):boot();
})();
