(()=>{
const STAFF=['David','Bénédicte','Séverine','Apprenti'];
const channel=('BroadcastChannel'in window)?new BroadcastChannel('gcos-comms-v3'):null;
const user=()=>{try{const s=JSON.parse(sessionStorage.getItem('jarvis-session')||'null'),a=JSON.parse(localStorage.getItem('jarvis-accounts')||'[]');return a.find(x=>x.id===s?.id)||{id:'inconnu',name:'Utilisateur'}}catch{return{id:'inconnu',name:'Utilisateur'}}};
const esc=s=>String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function speak(t,done){try{const u=new SpeechSynthesisUtterance(t);u.lang='fr-FR';u.rate=.95;u.onend=()=>done&&done();speechSynthesis.cancel();speechSynthesis.speak(u)}catch{done&&done()}}
function css(){if(document.getElementById('gcosRuntimeStyle'))return;const s=document.createElement('style');s.id='gcosRuntimeStyle';s.textContent=`
.gm{position:fixed;inset:0;z-index:40000;background:#02070cf2;display:grid;place-items:center;padding:16px}.gb{width:min(760px,100%);max-height:94vh;overflow:auto;background:linear-gradient(145deg,#11303b,#08171d);color:#fff;border:1px solid #4c8795;border-radius:24px;padding:22px;box-shadow:0 30px 100px #000}.gr{display:flex;gap:10px;flex-wrap:wrap}.gbtn{border:1px solid #4d7782;background:#173844;color:#fff;border-radius:13px;padding:12px 16px;font-weight:900;cursor:pointer}.gpri{background:linear-gradient(90deg,#91e9ff,#87cf6e);color:#061014;border:0}.gdanger{background:#b11212}.ginput,.gtextarea,.gselect{width:100%;padding:12px;margin:7px 0 13px;border:1px solid #426d78;border-radius:12px;background:#06151b;color:#fff}.photo-guide{text-align:center}.photo-guide .camera{font-size:5rem}.photo-guide h1{font-size:clamp(1.7rem,4vw,3rem)}.photo-count{display:inline-block;padding:7px 11px;border-radius:999px;background:#123b49;color:#b9f3ff}.flash{position:fixed;inset:0;z-index:50000;background:#b00000;color:#fff;display:grid;place-items:center;text-align:center;animation:fl .35s infinite alternate}.flash .ico{font-size:8rem}@keyframes fl{to{background:#ff2020}}#jarvisGlobalButton{position:fixed;left:16px;bottom:82px;z-index:15000;display:flex;align-items:center;gap:10px;border:1px solid #75e7ff88;border-radius:24px;padding:10px 14px 10px 10px;background:#071d2af2;color:#fff;box-shadow:0 0 36px #25cfff55;cursor:pointer}.jcore{display:grid;place-items:center;width:52px;height:52px;border-radius:50%;font-weight:1000;font-size:1.4rem;background:radial-gradient(circle,#fff 0 9%,#5de2ff 11% 25%,#087da5 28% 52%,#04131e 55%);box-shadow:0 0 20px #67e8ff}.jlab{display:flex;flex-direction:column;text-align:left}.jlab small{color:#b8efff}@media(max-width:650px){#jarvisGlobalButton{border-radius:50%;padding:10px}.jlab{display:none}}
`;document.head.appendChild(s)}
function modal(html){css();const d=document.createElement('div');d.className='gm';d.innerHTML='<div class="gb">'+html+'</div>';document.body.appendChild(d);return d}
function toast(t){const d=modal('<h2>'+esc(t)+'</h2><button class="gbtn gpri" id="ok">OK</button>');d.querySelector('#ok').onclick=()=>d.remove();setTimeout(()=>d.remove(),2200)}
function publish(type,priority,to,content){const m={type,priority,to,content,from:user().name,at:new Date().toISOString()};localStorage.setItem('gcos-last-message',JSON.stringify(m));const q=JSON.parse(localStorage.getItem('gcos-message-queue')||'[]');q.push(m);localStorage.setItem('gcos-message-queue',JSON.stringify(q.slice(-100)));channel&&channel.postMessage(m);return m}
function message(){const d=modal('<h2>💬 Contacter</h2><select class="gselect" id="to"><option value="">Choisir…</option>'+STAFF.map(x=>'<option>'+x+'</option>').join('')+'<option>Tout le personnel</option></select><textarea class="gtextarea" id="txt" rows="5" placeholder="Votre message…"></textarea><div class="gr"><button class="gbtn gpri" id="send">Envoyer</button><button class="gbtn" id="close">Fermer</button></div>');d.querySelector('#send').onclick=()=>{const to=d.querySelector('#to').value,txt=d.querySelector('#txt').value.trim();if(!to||!txt)return;publish('Message','Normale',to==='Tout le personnel'?STAFF:[to],txt);d.remove();speak('Message envoyé à '+to+'.')};d.querySelector('#close').onclick=()=>d.remove()}
function assistance(){const d=modal('<h2>🟠 Assistance</h2><p>Choisissez la seule personne à prévenir.</p><div class="gr">'+STAFF.filter(x=>x!==user().name).map(x=>'<button class="gbtn" data-n="'+esc(x)+'">'+esc(x)+'</button>').join('')+'</div><textarea class="gtextarea" id="why" rows="4" placeholder="Besoin d’aide…"></textarea><button class="gbtn" id="close">Annuler</button>');d.querySelectorAll('[data-n]').forEach(b=>b.onclick=()=>{const n=b.dataset.n,why=d.querySelector('#why').value.trim()||'Assistance demandée.';publish('Assistance','Haute',[n],why);d.remove();speak(n+' a été prévenu.')});d.querySelector('#close').onclick=()=>d.remove()}
function siren(){try{const A=window.AudioContext||window.webkitAudioContext,c=new A();for(let i=0;i<24;i++){const o=c.createOscillator(),g=c.createGain(),t=c.currentTime+i*.15;o.type='square';o.frequency.value=i%2?620:950;g.gain.setValueAtTime(.18,t);g.gain.exponentialRampToValueAtTime(.001,t+.13);o.connect(g);g.connect(c.destination);o.start(t);o.stop(t+.14)}setTimeout(()=>c.close(),4000)}catch{}}
function emergency(){css();const text='Urgence générale déclenchée par '+user().name;publish('Urgence','Critique',STAFF,text);siren();const d=document.createElement('div');d.className='flash';d.innerHTML='<div><div class="ico">🚨</div><h1>URGENCE GÉNÉRALE</h1><p>Tout le personnel a été alerté.</p><a class="gbtn gpri" href="tel:112">Appeler le 112</a> <button class="gbtn" id="ack">J’ai pris connaissance</button></div>';document.body.appendChild(d);d.querySelector('#ack').onclick=()=>d.remove()}
function installJarvis(){if(document.getElementById('jarvisGlobalButton')||!user())return;css();const b=document.createElement('button');b.id='jarvisGlobalButton';b.innerHTML='<span class="jcore">J</span><span class="jlab"><b>JARVIS</b><small>Parler maintenant</small></span>';b.onclick=()=>location.href='jarvis.html';document.body.appendChild(b)}

// STOCKAGE LOCAL DES PHOTOS DANS INDEXEDDB
function db(){return new Promise((res,rej)=>{const r=indexedDB.open('GCOSPhotos',1);r.onupgradeneeded=()=>r.result.createObjectStore('photos',{keyPath:'id'});r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}
async function storePhoto(file,meta){const d=await db();return new Promise((res,rej)=>{const tx=d.transaction('photos','readwrite');tx.objectStore('photos').put({id:meta.id,file,meta});tx.oncomplete=res;tx.onerror=()=>rej(tx.error)})}
function currentIntervention(){return localStorage.getItem('gcos-current-intervention')||'i1'}
const BEFORE=[
'Vue générale du véhicule, côté avant gauche.',
'Vue générale du véhicule, côté arrière droit.',
'Photo complète du dessous du véhicule.',
'Photo du compartiment moteur.',
'Passage de roue avant gauche.',
'Passage de roue avant droit.',
'Passage de roue arrière gauche.',
'Passage de roue arrière droit.'
];
const AFTER=[
'Vue complète du dessous après application du Dinitrol.',
'Train avant et zones traitées.',
'Train arrière et zones traitées.',
'Passage de roue avant gauche après traitement.',
'Passage de roue avant droit après traitement.',
'Passage de roue arrière gauche après traitement.',
'Passage de roue arrière droit après traitement.',
'Vue finale générale du véhicule.'
];
let flow=null;
function photoFlow(taskName,taskId){flow={taskName,taskId,phase:/dinitrol/i.test(taskName)?'apres-dinitrol':'controle-visuel',steps:/dinitrol/i.test(taskName)?AFTER:BEFORE,index:0,extra:0};showRequired()}
function photoUI(title,instruction,count,extra=false){const d=modal('<div class="photo-guide"><span class="photo-count">'+esc(count)+'</span><div class="camera">📷</div><h1>'+esc(title)+'</h1><p style="font-size:1.25rem">'+esc(instruction)+'</p><input id="cam" type="file" accept="image/*" capture="environment" hidden><div class="gr" style="justify-content:center"><button class="gbtn gpri" id="take">Ouvrir l’appareil photo</button>'+(extra?'<button class="gbtn gdanger" id="finish">Terminé — passer à la suite</button><button class="gbtn" id="voiceFinish">🎙 Dire « terminé »</button>':'')+'</div></div>');const input=d.querySelector('#cam');d.querySelector('#take').onclick=()=>input.click();input.onchange=async()=>{const f=input.files&&input.files[0];if(!f)return;const id=currentIntervention()+'-'+Date.now();await storePhoto(f,{id,interventionId:currentIntervention(),phase:flow.phase,task:flow.taskName,required:!extra,index:extra?flow.extra:flow.index,at:new Date().toISOString()});d.remove();if(extra){flow.extra++;askProblemThenContinue()}else{flow.index++;showRequired()}};if(extra){d.querySelector('#finish').onclick=()=>{d.remove();finishPhotoTask()};d.querySelector('#voiceFinish').onclick=()=>voiceFinish(d)}return d}
function showRequired(){if(flow.index>=flow.steps.length)return askExtras();const instruction=flow.steps[flow.index],n=flow.index+1,total=flow.steps.length;speak('Photo '+n+' sur '+total+'. '+instruction+' Prenez la photo maintenant.');photoUI('Photo obligatoire',instruction,n+' / '+total,false)}
function askExtras(){speak('Toutes les photos obligatoires sont prises. Avez-vous d’autres photos à ajouter ? Vous pouvez en prendre autant que nécessaire. Quand vous avez fini, dites terminé ou appuyez sur le bouton terminé.');photoUI('Photos obligatoires terminées','Prenez une photo supplémentaire, ou terminez cette étape.',flow.extra+' photo supplémentaire',true)}
function askProblemThenContinue(){const d=modal('<h2>Photo supplémentaire enregistrée</h2><p>Cette photo montre-t-elle une observation ou un problème à signaler ?</p><div class="gr"><button class="gbtn gdanger" id="yes">Oui, signaler un problème</button><button class="gbtn gpri" id="no">Non, autre photo</button><button class="gbtn" id="end">Terminé</button></div>');d.querySelector('#no').onclick=()=>{d.remove();askExtras()};d.querySelector('#end').onclick=()=>{d.remove();finishPhotoTask()};d.querySelector('#yes').onclick=()=>{d.remove();describeProblem()}}
function describeProblem(){const d=modal('<h2>Décrire le problème</h2><textarea class="gtextarea" id="desc" rows="4" placeholder="Exemple : corrosion perforante sur le bas de caisse droit…"></textarea><select class="gselect" id="level"><option>À surveiller</option><option>À traiter</option><option>Urgent</option></select><div class="gr"><button class="gbtn gpri" id="save">Ajouter au rapport</button><button class="gbtn" id="skip">Annuler</button></div>');d.querySelector('#save').onclick=()=>{const txt=d.querySelector('#desc').value.trim();if(!txt)return;addObservation(txt,d.querySelector('#level').value);d.remove();speak('Observation ajoutée au rapport. Vous pouvez prendre une autre photo ou terminer.');askExtras()};d.querySelector('#skip').onclick=()=>{d.remove();askExtras()}}
function addObservation(text,level){const id=currentIntervention(),k='gcos-work-'+id,s=JSON.parse(localStorage.getItem(k)||'{}');s.notes=s.notes||[];let rec=level==='Urgent'?'Faire contrôler et réparer avant de reprendre la route.':level==='À traiter'?'Prévoir un contrôle et une remise en état par un professionnel qualifié.':'Surveiller l’évolution et contrôler lors du prochain entretien.';s.notes.push({id:Date.now(),category:'Observation photo',text:text+' — Niveau : '+level+'. Préconisation : '+rec,at:new Date().toISOString(),vehicleRelated:true,automatic:true});localStorage.setItem(k,JSON.stringify(s))}
function voiceFinish(modalNode){const R=window.SpeechRecognition||window.webkitSpeechRecognition;if(!R)return toast('Reconnaissance vocale non disponible sur cet appareil.');const r=new R();r.lang='fr-FR';r.interimResults=false;r.onresult=e=>{const t=e.results[0][0].transcript.toLowerCase();if(t.includes('terminé')||t.includes('fini')||t.includes('suivant')){modalNode.remove();finishPhotoTask()}else speak('Je n’ai pas compris. Dites terminé.')};r.start();speak('Dites terminé lorsque vous avez fini les photos.')}
function finishPhotoTask(){const id=currentIntervention(),k='gcos-work-'+id,s=JSON.parse(localStorage.getItem(k)||'{}');s.checks=s.checks||[];const task=s.checks.find(x=>x.id===flow.taskId)||s.checks.find(x=>String(x.name).toLowerCase()===flow.taskName.toLowerCase());if(task){task.done=true;task.started=true}s.active=null;s.photos=s.photos||{};if(flow.phase==='controle-visuel'){s.photos.before=1;s.photos.under=1;s.photos.engine=1;s.photos.wheels=4}else{s.photos.dinitrol=1;s.photos.after=1}s.photoSessions=s.photoSessions||[];s.photoSessions.push({phase:flow.phase,required:flow.steps.length,extra:flow.extra,completedAt:new Date().toISOString()});localStorage.setItem(k,JSON.stringify(s));speak('Série de photos terminée et classée dans le dossier. Nous passons à la tâche suivante.');setTimeout(()=>location.reload(),1500)}
function patchChecklist(){if(!/employe\.html/i.test(location.pathname))return;document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;const task=b.closest('.task');if(!task)return;const strong=task.querySelector('strong');if(!strong)return;const name=strong.textContent.replace(/^\d+\.\s*/,'').trim();const txt=b.textContent.trim().toLowerCase();if(txt==='démarrer'){setTimeout(()=>{[...task.querySelectorAll('button')].forEach(x=>{if(x.textContent.includes('Valider la tâche'))x.textContent='Lancer'})},50)}if((txt==='lancer'||txt.includes('valider la tâche'))&&(/contrôle visuel initial/i.test(name)||/application dinitrol/i.test(name))){e.preventDefault();e.stopImmediatePropagation();const work=JSON.parse(localStorage.getItem('gcos-work-'+currentIntervention())||'{}');const t=(work.checks||[]).find(x=>x.name===name);photoFlow(name,t?.id)}},true);const obs=new MutationObserver(()=>{document.querySelectorAll('.task button').forEach(b=>{if(b.textContent.trim()==='Démarrer')b.textContent='Lancer';if(b.textContent.trim()==='Valider la tâche'){const n=b.closest('.task')?.querySelector('strong')?.textContent||'';if(/contrôle visuel initial|application dinitrol/i.test(n))b.textContent='Lancer'}})});obs.observe(document.body,{subtree:true,childList:true});}
window.GCOSComms={message,assistance,emergency};
document.addEventListener('DOMContentLoaded',()=>{installJarvis();patchChecklist()});
if(document.readyState!=='loading'){installJarvis();patchChecklist()}
})();