(()=>{'use strict';
if(window.__MAVIK_VOICE_LOADED__)return;window.__MAVIK_VOICE_LOADED__=true;
const script=document.currentScript;const ROOT=new URL('./',script?.src||location.href);const href=p=>new URL(p,ROOT).href;
const Recognition=window.SpeechRecognition||window.webkitSpeechRecognition;let recognition=null,listening=false,continuous=false,lastFocused=null,voiceTimer=null,listenersBound=false,observer=null;
function enabled(){return localStorage.getItem('mavik.voice.enabled')!=='0'}
function replies(){return localStorage.getItem('mavik.voice.reply')!=='0'}
function css(){if(document.getElementById('jarvisVoiceStyle'))return;const s=document.createElement('style');s.id='jarvisVoiceStyle';s.textContent=`#jarvisVoiceRoot{position:fixed;right:14px;bottom:14px;z-index:999980;font-family:Inter,system-ui,sans-serif}#jarvisVoiceButton{width:58px;height:58px;border-radius:50%;border:1px solid #44cde0;background:radial-gradient(circle at 40% 30%,#1b7186,#082333 65%);color:white;box-shadow:0 0 0 0 #19d8ef66,0 15px 40px #0009;font-size:1.45rem;cursor:pointer}#jarvisVoiceButton.listening{animation:jarvisPulse 1.2s infinite;background:radial-gradient(circle at 40% 30%,#3ba75a,#113621 65%)}@keyframes jarvisPulse{50%{box-shadow:0 0 0 13px transparent,0 15px 40px #0009}}#jarvisVoicePanel{position:absolute;right:0;bottom:68px;width:min(380px,calc(100vw - 28px));border:1px solid #286079;border-radius:16px;background:#061923;color:#f5fbff;padding:13px;box-shadow:0 22px 70px #000c}#jarvisVoicePanel[hidden]{display:none}#jarvisVoicePanel h3{margin:0 0 5px}#jarvisVoicePanel p{margin:4px 0;color:#9db8c4;font-size:.75rem}#jarvisVoiceTranscript{min-height:55px;max-height:145px;overflow:auto;border:1px solid #214d60;border-radius:10px;background:#020b11;padding:9px;margin:9px 0;white-space:pre-wrap;font-size:.78rem}#jarvisVoiceInput{width:100%;border:1px solid #2b6075;border-radius:9px;background:#031019;color:white;padding:9px}#jarvisVoicePanel .j-actions{display:flex;gap:7px;flex-wrap:wrap;margin-top:8px}#jarvisVoicePanel button{border:1px solid #2b6077;border-radius:9px;background:#0b2a3b;color:white;padding:8px 10px;cursor:pointer}#jarvisVoicePanel button.primary{background:#28603d;border-color:#4e9965;font-weight:900}#jarvisVoicePanel label{font-size:.72rem;color:#b7ced8}#jarvisVoiceStatus{display:inline-flex;border:1px solid #396c80;border-radius:999px;padding:3px 7px;font-size:.65rem}#jarvisVoiceStatus.on{border-color:#3d8355;color:#a8efbd}@media(max-width:700px){#jarvisVoiceRoot{bottom:78px;right:10px}#jarvisVoiceButton{width:52px;height:52px}}`;document.head.appendChild(s)}
function ui(){if(document.getElementById('jarvisVoiceRoot')||!enabled()||!document.body)return;const root=document.createElement('div');root.id='jarvisVoiceRoot';root.innerHTML=`<button id="jarvisVoiceButton" type="button" aria-label="Parler à Jarvis" title="Parler à Jarvis">🎙</button><section id="jarvisVoicePanel" hidden><div style="display:flex;justify-content:space-between;gap:8px"><div><h3>Jarvis vocal</h3><p>Navigation, dictée et actions autorisées.</p></div><span id="jarvisVoiceStatus">Prêt</span></div><div id="jarvisVoiceTranscript">Dites « ouvrir atelier », « nouveau devis » ou dictez dans un champ.</div><input id="jarvisVoiceInput" placeholder="Écrire une commande à Jarvis"><div class="j-actions"><button class="primary" id="jarvisTalk">Parler</button><button id="jarvisSend">Exécuter</button><button id="jarvisClose">Fermer</button></div><label><input type="checkbox" id="jarvisContinuous"> Mode vocal continu</label></section>`;document.body.appendChild(root);document.getElementById('jarvisVoiceButton').onclick=togglePanel;document.getElementById('jarvisTalk').onclick=startStop;document.getElementById('jarvisSend').onclick=()=>execute(document.getElementById('jarvisVoiceInput').value);document.getElementById('jarvisVoiceInput').onkeydown=e=>{if(e.key==='Enter')execute(e.target.value)};document.getElementById('jarvisClose').onclick=()=>document.getElementById('jarvisVoicePanel').hidden=true;document.getElementById('jarvisContinuous').onchange=e=>{continuous=e.target.checked;if(continuous&&!listening)start();if(!continuous&&listening)stop()};if(!listenersBound){document.addEventListener('focusin',e=>{if(e.target.matches('input:not([type=file]),textarea,[contenteditable=true]'))lastFocused=e.target});document.addEventListener('keydown',e=>{if(e.ctrlKey&&e.shiftKey&&e.key.toLowerCase()==='j'){e.preventDefault();togglePanel();start()}});listenersBound=true}}
function togglePanel(){const p=document.getElementById('jarvisVoicePanel');if(!p){ui();return}p.hidden=!p.hidden;if(!p.hidden)document.getElementById('jarvisVoiceInput')?.focus()}
function status(text,on=false){const s=document.getElementById('jarvisVoiceStatus');if(s){s.textContent=text;s.classList.toggle('on',on)}const b=document.getElementById('jarvisVoiceButton');b?.classList.toggle('listening',on)}
function transcript(text){const t=document.getElementById('jarvisVoiceTranscript');if(t){t.textContent=text;t.scrollTop=t.scrollHeight}}
function say(text){if(!replies()||!('speechSynthesis'in window))return;clearTimeout(voiceTimer);voiceTimer=setTimeout(()=>{speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang='fr-FR';u.rate=.98;u.pitch=.9;speechSynthesis.speak(u)},80)}
function initRecognition(){if(!Recognition)return null;const r=new Recognition();r.lang='fr-FR';r.interimResults=true;r.continuous=false;r.maxAlternatives=1;r.onstart=()=>{listening=true;status('Écoute…',true);transcript('Jarvis vous écoute…')};r.onresult=e=>{let interim='',final='';for(let i=e.resultIndex;i<e.results.length;i++){const txt=e.results[i][0].transcript;if(e.results[i].isFinal)final+=txt;else interim+=txt}transcript(final||interim);if(final)execute(final)};r.onerror=e=>{status('Erreur',false);transcript(`Reconnaissance vocale : ${e.error}`);listening=false};r.onend=()=>{listening=false;status('Prêt',false);if(continuous)setTimeout(start,350)};return r}
function start(){if(!document.getElementById('jarvisVoicePanel'))ui();const panel=document.getElementById('jarvisVoicePanel');if(panel)panel.hidden=false;if(!Recognition){transcript('La reconnaissance vocale n’est pas disponible dans ce navigateur. Utilisez la zone de commande écrite.');say('La reconnaissance vocale n’est pas disponible sur ce navigateur.');return}if(!recognition)recognition=initRecognition();try{recognition.start()}catch{}}
function stop(){continuous=false;const c=document.getElementById('jarvisContinuous');if(c)c.checked=false;try{recognition?.stop()}catch{}status('Prêt',false)}
function startStop(){listening?stop():start()}
function normalize(text){return String(text||'').trim().toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'')}
const routes=[[['atelier','poste atelier','dossier atelier'],'alpha/workshop/index.html'],[['planning','agenda','calendrier'],'planning.html'],[['gestion','clients','vehicules'],'gestion.html'],[['devis','estimations'],'devis.html'],[['reglages','profil','parametres'],'profil.html'],[['modules','tous les modules'],'modules.html'],[['suite operationnelle','operations'],'operations-suite.html'],[['ameliorations','idees'],'ameliorations.html'],[['tableau de bord','accueil'],'mavik-0411.html']];
function execute(raw){const original=String(raw||'').trim();if(!original)return;const text=normalize(original);const input=document.getElementById('jarvisVoiceInput');if(input)input.value='';transcript(`Vous : ${original}`);if(/^(stop|arrete|silence|fin du mode vocal)/.test(text)){stop();return respond('Mode vocal arrêté.')}if(/^(aide|que peux tu faire|commandes)/.test(text))return respond('Je peux ouvrir les pages, créer un dossier, un devis ou un rendez-vous, et remplir les champs par dictée.');if(/^(nouveau|creer|ouvre un nouveau) dossier/.test(text))return action('new-workshop','Ouverture d’un nouveau dossier.','alpha/workshop/index.html?new=1');if(/^(nouveau|creer|ouvre un nouveau) devis/.test(text))return action('new-quote','Ouverture d’un nouveau devis.','devis.html?new=1');if(/^(nouveau|creer|planifier|ajouter).*(rendez vous|rendez-vous|intervention)/.test(text))return action('new-appointment','Ouverture du planning.','planning.html?action=new');const navMatch=routes.find(([aliases])=>aliases.some(a=>text.includes(`ouvrir ${a}`)||text===a||text.includes(`va sur ${a}`)));if(navMatch){respond(`J’ouvre ${navMatch[0][0]}.`);setTimeout(()=>location.href=href(navMatch[1]),250);return}const fill=text.match(/^(?:remplir|renseigner|mettre)\s+(.+?)\s+(?:avec\s+)?(.+)$/);if(fill){const target=findField(fill[1]);if(target){setField(target,fill[2]);return respond(`${fieldName(target)} renseigné.`)}}if(lastFocused&&isEditable(lastFocused)){setField(lastFocused,original);return respond(`${fieldName(lastFocused)} renseigné.`)}if(text.startsWith('dicter ')){const target=document.activeElement;if(isEditable(target)){setField(target,original.slice(7));return respond('Dictée ajoutée.')}}const requests=JSON.parse(localStorage.getItem('mavik-ai-requests')||'[]');requests.unshift({id:crypto.randomUUID?.()||String(Date.now()),at:new Date().toISOString(),request:original,page:location.pathname,status:'À analyser',userId:JSON.parse(sessionStorage.getItem('jarvis-session')||'null')?.id||'guest'});localStorage.setItem('mavik-ai-requests',JSON.stringify(requests.slice(0,500)));respond('Je n’ai pas exécuté cette demande automatiquement. Je l’ai enregistrée pour analyse dans Jarvis.')}
function findField(alias){const a=normalize(alias);const fields=[...document.querySelectorAll('[data-voice-name],input:not([type=hidden]):not([type=file]),textarea,select')];return fields.find(f=>normalize(f.dataset.voiceName||f.name||f.id||f.closest('label')?.innerText||'').includes(a)||a.includes(normalize(f.dataset.voiceName||f.name||f.id||'')))}
function fieldName(el){return el.dataset.voiceName||el.name||el.id||'champ'}
function isEditable(el){return !!el&&el.matches?.('input:not([type=button]):not([type=submit]):not([type=file]),textarea,[contenteditable=true]')}
function setField(el,value){if(el.tagName==='SELECT'){const v=normalize(value),opt=[...el.options].find(o=>normalize(o.textContent).includes(v)||normalize(o.value)===v);if(opt)el.value=opt.value;else return}else if(el.isContentEditable)el.textContent=value;else{const append=el.tagName==='TEXTAREA'&&el.value.trim();el.value=append?`${el.value.trim()} ${value}`:value}el.dispatchEvent(new Event('input',{bubbles:true}));el.dispatchEvent(new Event('change',{bubbles:true}));el.focus();lastFocused=el}
function action(name,message,fallback){const button=document.querySelector(`[data-voice-action="${name}"]`);respond(message);setTimeout(()=>button?button.click():location.href=href(fallback),200)}
function respond(text){transcript(`Jarvis : ${text}`);say(text)}
function boot(){css();ui();window.JarvisVoice={start,stop,execute,say};observer=new MutationObserver(()=>{if(enabled()&&!document.getElementById('jarvisVoiceRoot'))ui()});observer.observe(document.documentElement,{childList:true,subtree:true})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot()
})();