(()=>{
  const CONFIG={
    prospects:{title:'Prospects',icon:'🎯',desc:'Demandes entrantes, véhicules ciblés, relances et transformation en client.',roles:['direction'],fields:[['name','Nom / société','text',true],['contact','Téléphone ou e-mail','text',true],['source','Origine','select',false,['Site internet','Téléphone','E-mail','Club','Événement','Réseau social','Partenaire','Autre']],['vehicle','Véhicule / besoin','text'],['status','Statut','select',true,['Nouveau','À qualifier','Devis à préparer','Devis envoyé','Relance','Gagné','Perdu']],['nextAction','Prochaine action','date'],['value','Montant estimé TTC','number'],['notes','Notes','textarea']]},
    partenaires:{title:'Partenaires',icon:'🤝',desc:'Partenaires techniques, commerciaux, clubs et apporteurs d’affaires.',roles:['direction'],fields:[['name','Nom / structure','text',true],['type','Type','select',true,['Technique','Commercial','Club automobile','Apporteur d’affaires','Institutionnel','Communication','Autre']],['contact','Contact','text'],['email','E-mail','email'],['phone','Téléphone','tel'],['status','Statut','select',true,['À contacter','Discussion','Accord à formaliser','Actif','Suspendu']],['agreement','Accord / contrepartie','textarea'],['notes','Notes','textarea']]},
    fournisseurs:{title:'Fournisseurs',icon:'🏭',desc:'Fournisseurs, contacts, conditions et suivi des commandes.',roles:['direction'],fields:[['name','Raison sociale','text',true],['category','Catégorie','select',true,['Glace carbonique','Dinitrol','Machine','Compresseur','Levage','EPI','Informatique','Aménagement','Transport','Autre']],['contact','Contact','text'],['email','E-mail','email'],['phone','Téléphone','tel'],['terms','Conditions / délais','textarea'],['status','Statut','select',true,['À référencer','Actif','En attente','Suspendu']],['notes','Notes','textarea']]},
    achats:{title:'Achats & commandes',icon:'🛒',desc:'Besoins, devis fournisseurs, commandes, livraisons et règlements.',roles:['direction'],fields:[['item','Article / prestation','text',true],['supplier','Fournisseur','text'],['category','Catégorie','select',true,['Équipement','Consommable','Stock','Aménagement','Service','Logiciel','Autre']],['amount','Montant TTC','number'],['orderDate','Date commande','date'],['deliveryDate','Livraison prévue','date'],['status','Statut','select',true,['Besoin identifié','Devis demandé','À valider','Commandé','Livré','Annulé']],['notes','Notes','textarea']]},
    stock:{title:'Stock opérationnel',icon:'❄️',desc:'Glace carbonique, Dinitrol, consommables, EPI et seuils d’alerte.',roles:['direction','employee'],fields:[['item','Produit','text',true],['category','Catégorie','select',true,['Glace carbonique','Dinitrol','Consommable','EPI','Pièce','Autre']],['quantity','Quantité','number',true],['unit','Unité','select',true,['kg','L','pièce','carton','bidon','lot']],['threshold','Seuil d’alerte','number'],['location','Emplacement','text'],['supplier','Fournisseur','text'],['status','État','select',true,['Disponible','À commander','Commandé','Rupture']],['notes','Notes','textarea']]},
    factures:{title:'Factures',icon:'🧾',desc:'Factures clients, échéances, statuts et règlements.',roles:['direction'],fields:[['number','Numéro de facture','text',true],['client','Client','text',true],['vehicle','Véhicule / prestation','text'],['amount','Montant TTC','number',true],['issueDate','Date émission','date'],['dueDate','Échéance','date'],['status','Statut','select',true,['Brouillon','À émettre','Envoyée','Partiellement réglée','Réglée','En retard','Annulée']],['paymentMethod','Règlement','select',false,['Virement','Carte / SumUp','Espèces','Non défini']],['notes','Notes','textarea']]},
    paiements:{title:'Paiements & encaissements',icon:'💳',desc:'Acomptes, soldes, encaissements et rapprochement des dossiers.',roles:['direction'],fields:[['reference','Référence','text',true],['client','Client / payeur','text',true],['type','Type','select',true,['Acompte 50 %','Solde','Facture pro','Remboursement','Autre']],['amount','Montant','number',true],['date','Date','date'],['method','Moyen','select',true,['Virement','Carte / SumUp','Espèces']],['status','Statut','select',true,['Attendu','Reçu','À rapprocher','Rapproché','Annulé']],['notes','Notes','textarea']]},
    rapports:{title:'Rapports',icon:'📋',desc:'Rapports d’intervention, contrôles, observations et documents à remettre.',roles:['direction','employee'],fields:[['reference','Référence dossier','text',true],['client','Client','text'],['vehicle','Véhicule','text',true],['type','Type','select',true,['Rapport intervention','Contrôle qualité','Rapport photo','Contrôle annuel','Incident']],['date','Date','date'],['status','Statut','select',true,['À compléter','À valider','Validé','Remis au client']],['summary','Résumé','textarea'],['recommendations','Préconisations','textarea']]},
    documents:{title:'Documents',icon:'📁',desc:'Index documentaire des devis, rapports, contrats, procédures et justificatifs.',roles:['direction','employee'],fields:[['name','Nom du document','text',true],['type','Type','select',true,['Devis','Facture','Rapport','Contrat','Procédure','Attestation','Photo','Courrier','Autre']],['related','Dossier / tiers lié','text'],['date','Date','date'],['location','Emplacement ou lien','text'],['confidentiality','Confidentialité','select',true,['Atelier','Interne','Direction','Données personnelles']],['status','Statut','select',true,['À classer','Classé','À signer','Signé','Archivé']],['notes','Notes','textarea']]},
    taches:{title:'Tâches',icon:'✅',desc:'Actions opérationnelles, priorités, responsables et échéances.',roles:['direction','employee'],fields:[['title','Tâche','text',true],['area','Domaine','select',true,['Atelier','Client','Fournisseur','Administratif','Communication','Maintenance','Sécurité','Autre']],['owner','Responsable','text'],['dueDate','Échéance','date'],['priority','Priorité','select',true,['Basse','Normale','Haute','Urgente']],['status','Statut','select',true,['À faire','En cours','Bloquée','Terminée']],['notes','Notes','textarea']]},
    equipe:{title:'Équipe & habilitations',icon:'👥',desc:'Fonctions, habilitations, formations et besoins des membres de l’équipe.',roles:['direction'],fields:[['name','Nom','text',true],['role','Fonction','text',true],['contract','Statut / contrat','select',false,['Associé','Salarié','Stagiaire','Formation','Sous-traitant','Autre']],['access','Habilitations accordées','textarea'],['training','Formations / compétences','textarea'],['status','Statut','select',true,['Prévu','Actif','Absent','Sorti']],['reviewDate','Revue des droits','date'],['notes','Notes','textarea']]},
    formations:{title:'Formations',icon:'🎓',desc:'Parcours internes, formations réglementaires et montée en compétence.',roles:['direction','employee'],fields:[['title','Formation','text',true],['person','Personne concernée','text'],['provider','Organisme / formateur','text'],['type','Type','select',true,['Interne','France Travail','Sécurité','Technique','Commercial','Logiciel','Autre']],['startDate','Début','date'],['endDate','Fin','date'],['status','Statut','select',true,['À prévoir','Planifiée','En cours','Terminée','À renouveler']],['proof','Justificatif / attestation','text'],['notes','Notes','textarea']]},
    evenements:{title:'Événements',icon:'🏁',desc:'Clubs, rallyes, journées partenaires, salons et actions locales.',roles:['direction','employee'],fields:[['name','Événement','text',true],['organizer','Organisateur','text'],['date','Date','date',true],['location','Lieu','text'],['type','Type','select',true,['Club automobile','Rallye','Salon','Démonstration','Partenariat','Institutionnel','Autre']],['objective','Objectif','textarea'],['status','Statut','select',true,['À étudier','À contacter','Confirmé','Préparé','Terminé','Annulé']],['budget','Budget TTC','number'],['notes','Notes','textarea']]},
    campagnes:{title:'Campagnes commerciales',icon:'📣',desc:'Campagnes, audiences, contenus, leads et résultats.',roles:['direction'],fields:[['name','Campagne','text',true],['channel','Canal','select',true,['Facebook','Instagram','E-mail','Site internet','Club','Événement','Partenaire','Autre']],['audience','Cible','text'],['startDate','Début','date'],['endDate','Fin','date'],['budget','Budget TTC','number'],['leads','Leads obtenus','number'],['status','Statut','select',true,['Idée','À préparer','Planifiée','Active','Terminée','Suspendue']],['result','Résultat / analyse','textarea']]},
    conformite:{title:'Conformité',icon:'⚖️',desc:'Obligations, preuves, contrôles juridiques et actions correctives.',roles:['direction'],fields:[['subject','Sujet / obligation','text',true],['domain','Domaine','select',true,['RGPD','Droit du travail','Consommateur','Facturation','Sécurité au travail','Environnement','Assurance','Société','Autre']],['source','Source officielle','text'],['reviewDate','Date de contrôle','date'],['nextReview','Prochaine revue','date'],['risk','Niveau de risque','select',true,['Faible','Modéré','Élevé','Critique']],['status','Statut','select',true,['À analyser','Conforme','Action requise','Bloquant','Archivé']],['action','Action / preuve','textarea']]},
    securite:{title:'Sécurité & accès',icon:'🔐',desc:'Habilitations, incidents de sécurité, équipements et contrôles périodiques.',roles:['direction'],fields:[['subject','Contrôle / incident','text',true],['type','Type','select',true,['Habilitation','Compte utilisateur','Incident informatique','Accès local','Caméra / alarme','Sauvegarde','Autre']],['owner','Responsable','text'],['date','Date','date'],['severity','Gravité','select',true,['Information','Faible','Modérée','Élevée','Critique']],['status','Statut','select',true,['Ouvert','En analyse','Action en cours','Résolu','Contrôle périodique']],['action','Mesures prises','textarea'],['notes','Notes','textarea']]},
    maintenance:{title:'Maintenance équipements',icon:'🔧',desc:'Machines, compresseur, levage, ventilation, contrôles et interventions.',roles:['direction','employee'],fields:[['equipment','Équipement','text',true],['type','Type','select',true,['Machine cryo','Compresseur','Levage','Ventilation','Électricité','Véhicule','Informatique','Autre']],['lastDate','Dernier contrôle','date'],['nextDate','Prochain contrôle','date'],['provider','Prestataire','text'],['status','État','select',true,['Opérationnel','À contrôler','Maintenance prévue','En panne','Immobilisé']],['cost','Coût TTC','number'],['action','Travaux / observations','textarea']]},
    incidents:{title:'Incidents & anomalies',icon:'🚨',desc:'Incidents atelier, anomalies client, sécurité, matériel et actions correctives.',roles:['direction','employee'],fields:[['title','Incident / anomalie','text',true],['area','Domaine','select',true,['Véhicule client','Atelier','Sécurité','Matériel','Transport','Données','Fournisseur','Autre']],['date','Date','date'],['reportedBy','Signalé par','text'],['severity','Gravité','select',true,['Faible','Modérée','Élevée','Critique']],['status','Statut','select',true,['Ouvert','Sécurisé','Analyse en cours','Action corrective','Clos']],['description','Description factuelle','textarea'],['action','Action / prévention','textarea']]},
    qualite:{title:'Qualité',icon:'⭐',desc:'Contrôles finaux, non-conformités, satisfaction et amélioration continue.',roles:['direction','employee'],fields:[['reference','Dossier / contrôle','text',true],['type','Type','select',true,['Contrôle final','Non-conformité','Satisfaction client','Audit interne','Amélioration']],['date','Date','date'],['owner','Contrôleur','text'],['score','Score / 100','number'],['status','Statut','select',true,['À réaliser','Conforme','Réserve','Action corrective','Validé']],['finding','Constat','textarea'],['action','Action décidée','textarea']]},
    assurances:{title:'Assurances',icon:'🛡️',desc:'Contrats, garanties, demandes de devis, échéances et sinistres.',roles:['direction'],fields:[['insurer','Assureur / courtier','text',true],['contract','Contrat / besoin','text',true],['coverage','Garanties','textarea'],['premium','Prime annuelle TTC','number'],['startDate','Début','date'],['renewalDate','Échéance','date'],['status','Statut','select',true,['Devis demandé','Étude','À souscrire','Actif','À renouveler','Résilié']],['contact','Contact','text'],['notes','Notes','textarea']]},
    financement:{title:'Financement',icon:'🏦',desc:'Dossiers bancaires, prêts, apports, échéances et pièces demandées.',roles:['direction'],fields:[['name','Financement / établissement','text',true],['type','Type','select',true,['Prêt bancaire','Apport capital','Compte courant','Crédit-bail','Subvention','Autre']],['amount','Montant','number'],['requestDate','Date demande','date'],['decisionDate','Date décision','date'],['status','Statut','select',true,['À préparer','Dossier envoyé','Complément demandé','Accord de principe','Accordé','Refusé','Décaissé']],['contact','Contact','text'],['documents','Pièces / conditions','textarea'],['notes','Notes','textarea']]},
    equipements:{title:'Équipements & investissements',icon:'⚙️',desc:'Inventaire des machines, outils, apports et investissements.',roles:['direction','employee'],fields:[['name','Équipement','text',true],['category','Catégorie','select',true,['Machine cryo','Compresseur','Levage','Outillage','EPI','Informatique','Mobilier','Véhicule','Autre']],['serial','Référence / série','text'],['value','Valeur TTC','number'],['acquiredDate','Date acquisition','date'],['location','Emplacement','text'],['status','État','select',true,['Prévu','Commandé','En service','Maintenance','Hors service','Cédé']],['notes','Notes','textarea']]},
    sousTraitants:{title:'Sous-traitants',icon:'🧰',desc:'Spécialistes externes, compétences, disponibilités, assurances et missions.',roles:['direction'],fields:[['name','Entreprise / personne','text',true],['specialty','Spécialité','text',true],['contact','Contact','text'],['insurance','Assurance / justificatif','text'],['rate','Tarif HT','number'],['availability','Disponibilité','text'],['status','Statut','select',true,['À qualifier','Référencé','Mission prévue','Actif','Suspendu']],['notes','Notes','textarea']]},
    journal:{title:'Journal de l’entreprise',icon:'📖',desc:'Décisions, événements importants, validations et historique GentleCarE.',roles:['direction'],fields:[['title','Événement / décision','text',true],['category','Catégorie','select',true,['Décision','Banque','Juridique','Fournisseur','Client','Atelier','Équipe','Communication','Autre']],['date','Date','date',true],['author','Auteur','text'],['status','Statut','select',true,['Information','À suivre','Validé','Clos']],['summary','Résumé','textarea',true],['next','Prochaine étape','textarea']]}
  };

  const moduleId=document.body.dataset.module;
  const cfg=CONFIG[moduleId];
  const $=id=>document.getElementById(id);
  const parse=(key,fallback=[])=>{try{return JSON.parse(localStorage.getItem(key)||'null')||fallback}catch{return fallback}};
  const session=parse('jarvis-session',null)||(()=>{try{return JSON.parse(sessionStorage.getItem('jarvis-session')||'null')}catch{return null}})();
  const accounts=parse('jarvis-accounts',[]);
  const user=accounts.find(a=>a.id===session?.id)||{id:'guest',name:'Utilisateur',role:'guest'};
  const allowed=cfg?.roles.includes(user.role)||user.role==='direction';
  const storeKey='mavik.module.'+moduleId+'.v1';
  let records=parse(storeKey,[]),editingId=null,toastTimer;
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#39;'}[c]));
  const labelOf=(field,value)=>value||'—';
  const now=()=>new Date().toISOString();

  function audit(action,record){const key='mavik-audit-log';const log=parse(key,[]);log.unshift({id:crypto.randomUUID?.()||String(Date.now()),at:now(),userId:user.id,userName:user.name,role:user.role,module:moduleId,action,recordId:record?.id||null,title:record?.[cfg.fields[0][0]]||''});localStorage.setItem(key,JSON.stringify(log.slice(0,2000)));}
  function notify(text,error=false){const el=$('toast');el.textContent=text;el.style.borderColor=error?'var(--red)':'var(--cyan)';el.hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.hidden=true,2800)}
  function roleName(){return user.role==='direction'?'Direction':user.role==='employee'?'Employé':'Non connecté'}
  function statusClass(value){const v=String(value||'').toLowerCase();if(/termin|valid|actif|régl|regl|conforme|livré|livre|clos|gagné|gagne|opérationnel|operationnel/.test(v))return'ok';if(/retard|rupture|bloqu|critique|refus|panne|annul|hors service/.test(v))return'danger';return'warn'}
  function titleValue(r){return r[cfg.fields[0][0]]||cfg.title}
  function secondary(r){return cfg.fields.slice(1,4).map(f=>r[f[0]]).filter(Boolean).join(' · ')||'Enregistrement MAVIK'}

  function layout(){
    if(!cfg){document.body.innerHTML='<main class="empty"><h1>Module inconnu</h1><a class="btn" href="modules.html">Retour aux modules</a></main>';return}
    document.title='MAVIK — '+cfg.title;
    document.body.innerHTML=`<div class="shell"><aside class="side"><div class="brand"><img src="assets/brand/gentlecare-logo.png" alt="GentleCarE"><small>${esc(cfg.title)}</small></div><nav class="nav"><a href="index.html">⌂ <span>Accueil</span></a><a href="modules.html">▦ <span>Tous les modules</span></a><a href="alpha/workshop/index.html">🛠 <span>Atelier</span></a><a href="planning.html">▣ <span>Planning</span></a><a href="gestion.html">◈ <span>Gestion</span></a><a href="ameliorations.html">💡 <span>Améliorations</span></a></nav><div class="side-foot"><strong>MAVIK 0.40.0</strong><small>● Page autonome</small></div></aside><main class="main"><header class="topbar"><strong>${esc(cfg.icon+' '+cfg.title)}</strong><div class="user"><div class="avatar" id="avatar">?</div><div><strong id="userName">Utilisateur</strong><small class="muted" id="userRole">Session</small></div><a class="btn" href="update.html">Mise à jour</a></div></header><div class="content"><section class="hero"><div><h1>${esc(cfg.icon+' '+cfg.title)}</h1><div class="muted">${esc(cfg.desc)}</div></div><div class="actions"><button class="btn primary" id="newBtn">+ Ajouter</button><button class="btn" id="exportBtn">Exporter JSON</button></div></section><section class="metrics" id="metrics"></section><section class="layout"><article class="card"><h2>Informations du module</h2><p class="muted">Les données sont conservées sur cet appareil et chaque modification est inscrite au journal MAVIK.</p><div id="accessInfo"></div><div class="actions" style="margin-top:12px"><a class="btn" href="ameliorations.html">Proposer une amélioration</a><a class="btn" href="journal.html">Journal entreprise</a></div></article><article class="card"><div class="toolbar"><div><h2>Registre</h2><div class="muted" id="count"></div></div><input class="search" id="search" placeholder="Rechercher"></div><div class="list" id="list"></div></article></section></div></main></div><nav class="mobilebar"><a href="index.html"><b>⌂</b>Accueil</a><a href="modules.html"><b>▦</b>Modules</a><a href="alpha/workshop/index.html"><b>🛠</b>Atelier</a><a href="planning.html"><b>▣</b>Planning</a><a href="ameliorations.html"><b>💡</b>Idées</a></nav><div class="modal" id="modal"><form class="modal-box" id="form"><div class="toolbar"><div><div class="muted">${esc(cfg.title.toUpperCase())}</div><h2 id="formTitle">Nouvel enregistrement</h2></div><button class="btn" type="button" id="closeBtn">Fermer</button></div><div class="form" id="fields"></div><div class="actions" style="justify-content:flex-end;margin-top:13px"><button class="btn" type="button" id="cancelBtn">Annuler</button><button class="btn primary" type="submit">Enregistrer</button></div></form></div><div class="toast" id="toast" hidden></div>`;
  }

  function fieldHtml([name,label,type,required,options]){
    const wide=type==='textarea'?'wide':'';
    if(type==='textarea')return`<label class="${wide}">${esc(label)}<textarea name="${esc(name)}" ${required?'required':''}></textarea></label>`;
    if(type==='select')return`<label>${esc(label)}<select name="${esc(name)}" ${required?'required':''}>${(options||[]).map(v=>`<option value="${esc(v)}">${esc(v)}</option>`).join('')}</select></label>`;
    return`<label>${esc(label)}<input name="${esc(name)}" type="${esc(type||'text')}" ${required?'required':''} ${type==='number'?'step="0.01"':''}></label>`;
  }
  function openForm(record=null){if(!allowed){notify('Accès réservé à la Direction.',true);return}editingId=record?.id||null;$('formTitle').textContent=record?'Modifier':'Nouvel enregistrement';$('fields').innerHTML=cfg.fields.map(fieldHtml).join('');if(record)cfg.fields.forEach(([name])=>{const el=$('form').elements[name];if(el)el.value=record[name]??''});$('modal').classList.add('open')}
  function closeForm(){$('modal').classList.remove('open');editingId=null}
  function saveRecord(event){event.preventDefault();if(!allowed)return;const data=Object.fromEntries(new FormData($('form')));const existing=records.find(r=>r.id===editingId);const record={...(existing||{}),...data,id:editingId||crypto.randomUUID?.()||String(Date.now()),createdAt:existing?.createdAt||now(),updatedAt:now(),updatedBy:user.name};records=editingId?records.map(r=>r.id===editingId?record:r):[record,...records];localStorage.setItem(storeKey,JSON.stringify(records));audit(editingId?'record.updated':'record.created',record);closeForm();render();notify('Enregistrement sauvegardé')}
  function removeRecord(id){if(!allowed)return;const record=records.find(r=>r.id===id);if(!record||!confirm('Supprimer cet enregistrement ?'))return;records=records.filter(r=>r.id!==id);localStorage.setItem(storeKey,JSON.stringify(records));audit('record.deleted',record);render();notify('Enregistrement supprimé')}
  function renderMetrics(){const statusField=cfg.fields.find(f=>f[0]==='status');const today=new Date().toISOString().slice(0,10);const dateFields=cfg.fields.filter(f=>f[2]==='date').map(f=>f[0]);const due=records.filter(r=>dateFields.some(k=>r[k]&&r[k]>=today)).length;const alerts=statusField?records.filter(r=>statusClass(r.status)==='danger').length:0;const complete=records.filter(r=>cfg.fields.filter(f=>f[3]).every(f=>String(r[f[0]]??'').trim())).length;$('metrics').innerHTML=[['Enregistrements',records.length],['Complets',complete],['À venir',due],['Alertes',alerts]].map(([l,v])=>`<article class="metric"><span>${l}</span><strong>${v}</strong></article>`).join('')}
  function renderList(){const q=($('search').value||'').toLowerCase();const list=records.filter(r=>Object.values(r).join(' ').toLowerCase().includes(q)).sort((a,b)=>String(b.updatedAt||'').localeCompare(String(a.updatedAt||'')));$('count').textContent=records.length+' enregistrement(s)';$('list').innerHTML=list.length?list.map(r=>{const status=r.status||r[cfg.fields.find(f=>f[0]==='priority')?.[0]]||'Enregistré';const details=cfg.fields.slice(1,7).filter(f=>r[f[0]]!==undefined&&r[f[0]]!=='').map(f=>`<div class="detail"><b>${esc(f[1])}</b><br>${esc(labelOf(f,r[f[0]]))}</div>`).join('');const actions=allowed?`<div class="actions" style="margin-top:10px"><button class="btn" data-edit="${r.id}">Modifier</button><button class="btn danger" data-delete="${r.id}">Supprimer</button></div>`:'';return`<article class="record"><div class="record-head"><div><strong>${esc(titleValue(r))}</strong><small>${esc(secondary(r))}</small></div><span class="pill ${statusClass(status)}">${esc(status)}</span></div><div class="record-details">${details}</div>${actions}</article>`}).join(''):'<div class="empty">Aucun enregistrement. Utilisez « Ajouter » pour commencer.</div>'}
  function renderAccess(){const el=$('accessInfo');if(allowed)el.innerHTML=`<span class="pill ok">Accès ${esc(roleName())}</span><p>Vous pouvez consulter et modifier ce module.</p>`;else el.innerHTML=`<div class="denied"><strong>Accès limité</strong><p>Ce module contient des informations sensibles réservées à la Direction. Votre demande d’accès doit passer par le dossier Améliorations et une validation d’habilitation.</p><a class="btn" href="ameliorations.html">Demander une fonction adaptée</a></div>`;$('newBtn').hidden=!allowed}
  function exportData(){const blob=new Blob([JSON.stringify({module:moduleId,title:cfg.title,exportedAt:now(),records},null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='mavik-'+moduleId+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500);audit('module.exported',{id:null})}
  function render(){renderMetrics();renderList();renderAccess()}

  layout();if(!cfg)return;$('avatar').textContent=(user.name||'?')[0].toUpperCase();$('userName').textContent=user.name;$('userRole').textContent=roleName();$('newBtn').onclick=()=>openForm();$('exportBtn').onclick=exportData;$('closeBtn').onclick=closeForm;$('cancelBtn').onclick=closeForm;$('form').onsubmit=saveRecord;$('search').oninput=renderList;$('list').onclick=e=>{const edit=e.target.closest('[data-edit]'),del=e.target.closest('[data-delete]');if(edit)openForm(records.find(r=>r.id===edit.dataset.edit));if(del)removeRecord(del.dataset.delete)};$('modal').onclick=e=>{if(e.target===$('modal'))closeForm()};render();
})();